version: "3.5" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  mysql: # 서비스 명
    image: mysql:5.7 # 사용할 이미지
    container_name: silvatools-mysql # 컨테이너 이름 설정
    #restart: always
    ports:
      - "3310:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "root"  # MYSQL 패스워드 설정 옵션
      MYSQL_USER: "silva"
      MYSQL_PASSWORD: "silva"
      MYSQL_DATABASE: "silvatools"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      #- --default-authentication-plugin=mysql_native_password
    volumes:
      - "./_init_sql/:/docker-entrypoint-initdb.d/"  # init 폴더에 sql 을 넣어두면 구동 시, 자동 실행
      - ./mysql/silvatools:/var/lib/mysql # -v 옵션 (디렉토리 마운트 설정)

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: silvatools-rabbit
    hostname: silvatools-rabbitmq
    #restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "silva"
      RABBITMQ_DEFAULT_PASS: "silva"
    ports:
      - "5680:5672"
      - "15680:15672"
    volumes:
      - ./rabbitmq/etc:/etc/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq/log

  redis:
    image: "redis:3.2.11"
    container_name: silvatools-redis
    hostname: silvatools-redis
    #restart: always
    ports:
      - '6380:6379'
    command: redis-server --requirepass adminadmin